"""add api token

Revision ID: 35810a37b3a4
Revises: 10708a59644f
Create Date: 2026-03-08 16:00:49.761149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35810a37b3a4'
down_revision = '10708a59644f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
