"""add ml fields to user and application

Revision ID: f9551bb3f1fb
Revises: 8df0cd67f55d
Create Date: 2026-03-20 09:51:13.795290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9551bb3f1fb'
down_revision = '8df0cd67f55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('response_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('backlogs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('college', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('internship_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('project_count')
        batch_op.drop_column('internship_count')
        batch_op.drop_column('branch')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('college')
        batch_op.drop_column('backlogs')
        batch_op.drop_column('cgpa')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('response_days')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('source')
        batch_op.drop_column('salary')
        batch_op.drop_column('job_type')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
